version: 2
jobs:
  publish:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - run: npm publish
  build:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn build-storybook
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - deploy:
          name: Deploy to Now
          command: |
            GIT_HASH=$(git rev-parse --short HEAD)
            SANITIZED_BRANCH=$(tr "/" "-" <<<$CIRCLE_BRANCH)
            VERY_SANITIZED_BRANCH=$(tr "." "-" <<<$SANITIZED_BRANCH)
            BUILD_URL=$(npx now storybook-static --name react-trivial-timeline -t $NOW_DEVELOPMENT_TOKEN --public)
            npx now alias ${BUILD_URL} ${GIT_HASH}-react-trivial-timeline -t $NOW_DEVELOPMENT_TOKEN
            npx now alias ${BUILD_URL} ${VERY_SANITIZED_BRANCH}-react-trivial-timeline -t $NOW_DEVELOPMENT_TOKEN
workflows:
  version: 2
  tagged-build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
